version: "3.9"  # optional since v1.27.0

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "3000:3000"

  notifier-polkadot:
    environment:
      network: "Polkadot"
      defaultHeight: "7647081"
    build:
      context: .
      dockerfile: ./docker/notifier/Dockerfile

  notifier-kusama:
    environment:
      network: "Kusama"
      defaultHeight: "10038895"
    build:
      context: .
      dockerfile: ./docker/notifier/Dockerfile

  scanner-polkadot:
    environment:
      network: "Polkadot"
      defaultHeight: "7647081"
    build:
      context: .
      dockerfile: ./docker/scanner/Dockerfile

  scanner-kusama:
    environment:
      network: "Kusama"
      defaultHeight: "10038895"
    build:
      context: .
      dockerfile: ./docker/scanner/Dockerfile

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

